version: "3.8"

services:
  placeholder-api:
    container_name: placeholder-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - GIN_MODE=release  # si tu utilises Gin par ex
    volumes:
      - ./fonts:/app/placeholder-api/fonts
